version: '3.8'

services:
  # fastapi:
  #   build: .
  #   container_name: summarizer
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - .:/app  
  #   env_file:
  #     - .env
  #   depends_on:
  #     - ollama 
  #   restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_server
    ports:
      - "11434:11434"
    mem_limit: 9g
    volumes:
      - ./ollama_data:/root/.ollama
      - ./entrypoint.sh:/app/entrypoint.sh
    restart: unless-stopped